### ISSUE TITLE
Respect the [required] attribute during type specfication

### ISSUE THREAD

**Issue by jzbrooks** [FacilityApi/FacilityCSharp#22]
A related issue on the core project: https://github.com/FacilityApi/Facility/issues/24

The Faithlife app employs the Kotlin and Swift programming languages on Android and iOS respectively. The code generator used to generate client code respects the `[required]` attribute to make use of the languages' type systems that model nullability. Currently, the C# code generator used to generate BFF code for the apps still outputs nullable value types (pre C# 8) even if the `[required]` attribute is specified, weakening the contract between client and server by making it more of a convention in this case.

With C# 8's more extensive null modeling in its type system, it could be even more useful.

**Comment by ejball** [comment]
Though I can imagine supporting a `Validate` method to ensure that required fields are set, I'm not sure I'm prepared to make required fields non-nullable in the DTOs. Unless I'm convinced otherwise, the C# 8 change I would make would be to make reference types nullable, even when required.

This DTO produces a warning in C# 8 because the property is non-nullable but not initialized:

```csharp
class WidgetDto
{
	public string Name { get; set; }
}
```

To fix the warning, we can (1) make `Name` nullable, we can (2) assign it to some default value (the empty string, presumably), or we can (3) add a constructor. I'm definitely opposed to (2). I have various objections to (3) -- I don't like the look of DTOs that are created partially via constructor and partially be property assignment; constructors make binary compatibility difficult as properties are added or changed; perhaps others if I think about it more -- so I'm inclined to stick with (1) so far.

**Comment by jzbrooks** [comment]
My thoughts are more geared toward Kotlin & Swift consumers than C# ones. I'm not really that caught up on C# 8 yet.

In Kotlin and Swift, the compiler requires that a null check is performed if a property is nullable (swift uses the term optional). This can lead to really verbose code for things that are always specified, like an id. The [required] attribute has been useful for consuming code to more correctly model the availability of certain properties on a dto. Right now, the server side of things is responsible for respecting the specification of `[required]` in the FSD in an ad-hoc way, which is prone to user error. If the C# generator took `[required]` into account, it would force the server implementation to handle null appropriately (which for some consumers in very similar to handling _types_ correctly).

Considering situations [like this](https://git/Logos/FaithlifeMobileApi/blob/5be020cdf8c380510a9b3c1ab2c4bc59d4d334b4/src/Faithlife.MobileApi.v1.Services/Mappers/AccountMapper.cs#L84), it would force the server implementation to uphold the demand that the value is always specified.

Making all those properties nullable makes for a lot more code client side. There isn't a `.Value` property like `Nullable<T>` in C#.

**Kotlin**
```kotlin
accountDto.Id?.let { id ->
  // safe to use id
}
```

**Swift**
```swift
if let id = accountDto.Id {
  // safe to use id
}
```

If every property on the dto is specified as nullable in our client side dto, it makes for some pretty paranoid code that could obscure the code's purpose.

In languages where nullablity is built into the type system it isn't truly representative of the dto to make everything nullable.

**Comment by ejball** [comment]
Until C# has better DTO support (via "records", perhaps), DTO properties will remain nullable, but we could achieve the desired effect via [validation](#23).
